/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 02c7d386248c4ce9893c8d3b6dd6a2b9)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat" | "SessionMemoryDO";
	}
	interface Env {
		VISION_MODEL_ID: string;
		STRUCTURE_MODEL_ID: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		SESSION_MEMORY: DurableObjectNamespace<import("./src/server").SessionMemoryDO>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VISION_MODEL_ID" | "STRUCTURE_MODEL_ID">> {}
}
